#tag BuildAutomation
			Begin BuildStepList Linux
				Begin BuildProjectStep Build
				End
			End
			Begin BuildStepList Mac OS X
				Begin BuildProjectStep Build
				End
				Begin CopyFilesBuildStep CopyTests
					AppliesTo = 0
					Destination = 1
					Subdirectory = 
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzMyLXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzMyLm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzMzLXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzMzLm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzM0LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzM0Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzM1LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzM1Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzM2LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzM2Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzM3LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzM3Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzM4LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzM4Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzM5LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzM5Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQwLXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQwLm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQxLXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQxLm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQyLXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQyLm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQzLXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQzLm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQ0LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQ0Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQ1LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQ1Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQ2LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQ2Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQ4LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQ4Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQ5LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzQ5Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzc3LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzc3Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzgwLXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzgwLm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzgxLXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzgxLm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzgyLXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzgyLm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzgzLXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzgzLm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzg0LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzg0Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzg2LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzg2Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzg3LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzg3Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzg4LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzg4Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzg5LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzg5Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzkwLXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzkwLm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzkyLXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzkyLm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzkzLXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzkzLm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzk0LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzk0Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzk1LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzk1Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzk2LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzk2Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzk3LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzk3Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzk4LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzk4Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzk5LXBoYXNlMS5hc3Q=
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzk5Lm1k
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwMC1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwMC5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwMS1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwMS5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwMi1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwMi5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwMy1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwMy5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwNC1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwNC5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwNS1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwNS5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwNi1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwNi5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwNy1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwNy5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwOC1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzEwOC5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzExMC1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzExMC5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzExMi1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzExMi5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzExMy1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzExMy5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzExNC1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzExNC5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzExNi1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzExNi5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzExNy1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzExNy5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzE5OC1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzE5OC5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzE5OS1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzE5OS5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzIwMC1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzIwMC5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzIwMS1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzIwMS5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzIwMi1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzIwMi5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzIwMy1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzIwMy5tZA==
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzIwNi1waGFzZTEuYXN0
					FolderItem = Li4vLi4vdGVzdHMvcGhhc2UxLzIwNi5tZA==
				End
			End
			Begin BuildStepList Windows
				Begin BuildProjectStep Build
				End
			End
#tag EndBuildAutomation
